name: Eric Lawton
title: Social Systems Thinking
description: A workbook in the use of tools for thinking about social systems
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
github: [metadata]

plugins:
  - jekyll-seo-tag

theme: jekyll-theme-midnight
# remote_theme: pages-themes/midnight@v0.2.0
