name: Eric Lawton
title: Better social systems for better lives
description: A social and political philosophy workbook
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
github: [metadata]
plugins:
  - jekyll-seo-tag

theme: jekyll-theme-midnight