name: Eric Lawton
title: A philosophy workbook as a document and blog
description: A social and political philosophy book with a blog annotating its construction
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
github: [metadata]
plugins:
  - jekyll-seo-tag
